# These are supported funding model platforms

github: ELMOURABEA
patreon: ELMOURABEA
open_collective: ELMOURABEA
ko_fi: ELMOURABEA
tidelift: npm/ELMOURABEA
liberapay: ELMOURABEA
issuehunt: ELMOURABEA
polar: ELMOURABEA
buy_me_a_coffee: ELMOURABEA
thanks_dev: ELMOURABEA
custom: ["https://github.com/sponsors/ELMOURABEA"]
